[workspace]
authors = ["Robert Cocker <rcocker87@gmail.com>"]
channels = ["conda-forge"]
name = "advent-of-code"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
bandit = ">=1.9.2,<2"
pip-audit = ">=2.9.0,<3"
clang = ">=21.1.6,<22"
gcc = ">=15.2.0,<15.3"
gfortran = ">=15.1.0,<15.3"
cmake = ">=4.2.0,<5"
