[workspace]
authors = ["Robert Cocker <rcocker87@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "advent-of-code"
platforms = ["linux-64", "osx-arm64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
bandit = ">=1.9.2,<2"
pip-audit = ">=2.9.0,<3"
clang = ">=21.1.6,<22"
gcc = ">=15.2.0,<15.3"
gfortran = ">=15.1.0,<15.3"
cmake = ">=4.2.0,<5"
libcxx = ">=8.0.0,<22"
clang-tools = ">=21.1.6,<22"
clang-format = ">=21.1.6,<22"
mojo = ">=0.26.1.0.dev2025120105,<0.27"
mojo-compiler = ">=0.26.1.0.dev2025120105,<0.27"
